language: node_js 
node_js:
  - "v14.16.0"
handlers:
  - url: /(.*)\.js
    script: \app.js
steps:
  - task: AzureWebApp@1
  displayName: Azure App Service Deploy
  inputs:
    azureSubscription: 'Azure for Students'
    appName: 'MyKuduBuddy'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip')'
    customWebConfig: '-Handler iisnode -NodeStartFile app.js -appType node'

deploy:
  provider: azure_web_apps
  username: kadel08       # If AZURE_WA_USERNAME isn't set
  password: Elijah@1005   # If AZURE_WA_PASSWORD isn't set
  site: ThisIsJustATrial       # If AZURE_WA_SITE isn't set
  verbose: true
  on:
    branch: main
      
